spring:
  profiles:
    active: front
  datasource:
    url: jdbc:mysql://rm-bp18cz0lra064znmono.mysql.rds.aliyuncs.com/search?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: '!@#123qwe'
mybatis:
  mapperLocations: classpath:mapper/*.xml

---

spring:
  datasource:
    url: jdbc:mysql://rm-bp18cz0lra064znmono.mysql.rds.aliyuncs.com/search?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: '!@#123qwe'
  config:
    activate:
      on-profile: dev
mybatis:
  mapperLocations: classpath:mapper/*.xml

---

spring:
  datasource:
    url: jdbc:mysql://rm-bp18cz0lra064znmono.mysql.rds.aliyuncs.com/search?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: '!@#123qwe'
  config:
    activate:
      on-profile: front
mybatis:
  mapperLocations: classpath:mapper/*.xml
