spring:
  #数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/search?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 292918726
mybatis:
  mapperLocations: classpath:mapper/*.xml
