#这个配置是服务器上线环境配置
spring:
  profiles:
    active:
  datasource:
    url: jdbc:mysql://rm-bp18cz0lra064znmono.mysql.rds.aliyuncs.com/search?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: '!@#123qwe'
mybatis:
  mapperLocations: classpath:mapper/*.xml
mapper:
  mappers: com.eytins.sar_admin.framework.baseMapper.MyMapper
  notEmpty: true

---

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/search?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 292918726
  config:
    activate:
      on-profile: dev
mybatis:
  mapperLocations: classpath:mapper/*.xml
mapper:
  mappers: com.eytins.sar_admin.framework.baseMapper.MyMapper
  notEmpty: true

---

spring:
  datasource:
    url: jdbc:mysql://rm-bp18cz0lra064znmono.mysql.rds.aliyuncs.com/search?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: '!@#123qwe'
  config:
    activate:
      on-profile: front
  thymeleaf:
    cache: off
mybatis:
  mapperLocations: classpath:mapper/*.xml
mapper:
  mappers: com.eytins.sar_admin.framework.baseMapper.MyMapper
  notEmpty: true